name: Kwiki-Purple
version: 0.02
abstract: Provides purple numbers support to Kwiki
author: Chris Dent <cdent@burningchrome.com>
license: perl
distribution_type: module
requires:
  Kwiki: 0.37
  Kwiki::Test: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
