name: Kwiki-Purple
version: 0.03
abstract: Provides purple numbers support to Kwiki
author: Chris Dent <cdent@burningchrome.com>
license: perl
distribution_type: module
requires:
  Kwiki: 0.38
  Kwiki::Test: 0.03
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
